Setup Models
Anand8317/blog pull request #1
Opened 2023-09-23 18:16 UTC by Anand8317

Added four models - User, Post, Comments, Likes
Added associations between them.
Added index on foreign key

2023-09-23 18:34 UTC, danmainah requested changes
Hi @Anand8317 , 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
✔️  Added migration files for the users, posts, comments and likes tables
✔️ Ensured the migrations are running successfully.


# Required Changes ♻️
_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s).

2023-09-23 18:34 UTC, danmainah commented on README.md
> +
- [ ] @Anand8317 Kindly consider adding a license file, that legal allows user to clone and use your project.

2023-09-23 18:34 UTC, danmainah commented on README.md
> +
- [ ] [optional] It would be nice adding how to run the app after cloning the app.

2023-09-23 18:34 UTC, danmainah commented on db/migrate/20230923173458_create_posts.rb
> +      t.references :user, null: false, foreign_key: true
- [ ] @Anand8317 Great work adding the post table, however, the reference to user should use author instead of user, you can use the code below 
``` t.references :author, foreign_key: { to_table: 'users' }```

![image](https://github.com/Anand8317/blog/assets/61408860/8143986d-1de9-457c-8c41-3d48b3347358)

2023-09-23 18:34 UTC, danmainah commented on config/database.yml
> +  timeout: 5000
- [ ] @Anand8317 Kindly consider changing the database adapter to using Postgresql as the project instruction.

![image](https://github.com/Anand8317/blog/assets/61408860/df3bd8dc-ee4a-49f6-83f6-4e3b64779230)

2023-09-23 19:35 UTC, topeogunleye approved these changes
### Hi @Anand8317, 

# Status: Approved ✔️
Excellent job on making the changes requested by the previous code reviewer. Keep it up 👏

Your project is complete! There is nothing else to say other than... it's time to merge it 💪
Congratulations! 🎉
![congratulations](https://user-images.githubusercontent.com/52934128/163691476-087b4b9c-825b-40a3-85a1-d1bde44ffa53.gif)
>
## To highlight :champagne: 
- Added MIT License. ✔️ 
- Added reference to user should use author instead of the user using the code given. ✔️ 
- Changed the database adapter to use Postgresql. ✔️ 
 
## [Optional] suggestions:
* [ ]  Please check my inline comments.
 
 _Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._
 
Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.



------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-09-23 20:44 UTC, merged

2023-09-30 16:21 UTC, Ibizugbe reviewed
Hi @Anand8317 👋🏼👋🏼👋🏼, 

![approved](https://github.com/Anand8317/blog/assets/64643995/ca6ec0b0-7122-455d-8f16-3a63c4358500)


Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights✅✅✅

- [x] Project has met the technical requirements for this milestone👍🏼.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._